### ISSUE TITLE
Thread safety and performance

### ISSUE THREAD

**Issue by hgani** [yhirose/maxminddb#17]
Hi,

I am trying to figure out the most efficient way to use this gem in a Rails app.

Will it be more efficient if I cache the instance as a class-level constant? For example:

GEO_DB = MaxMindDB.new('./GeoLite2-City.mmdb')

def detect_country
  ret = GEO_DB.lookup('74.125.225.224')
  ret.country.name
end

This is so that all requests can use the same instance.

Does this gem perform any write operation? I assume if it doesn't then it must be thread safe, right?

Thanks

**Comment by peterept** [comment]
I hope so, because this is how I do it:

config/initializers/maxminddb.rb:
```ruby
# Download latest free geo city database from here:
# http://dev.maxmind.com/geoip/geoip2/geolite2/
Maxminddb = MaxMindDB.new("#{Rails.root}/geo/GeoLite2-City.mmdb")
```

Then where-ever I need it, I just call:
```ruby
geo = Maxminddb.lookup(ipaddress)
```

**Comment by yhirose** [comment]
Thank you for the question and comment.

A MaxMindDB instance doesn't do any write operation after it is created. So we can consider it as an immutable object which is 'thread-safe'. 

Please see how the member variables, `@path`, `@data` and `@metadata` on `class Client` used in [libmaxminddb.rb](https://github.com/yhirose/maxminddb/blob/master/lib/maxminddb.rb). You can see that these variables will never be changed after they are initialized in `def initialize` method.

You can also confirm the immutability with the following code:

```ruby
db = MaxMindDB.new('./GeoLite2-City.mmdb')
db.freeze
db.frozen? # => true
db.lookup('74.125.225.224').found? # => true. This call doesn't throw '#<RuntimeError: can't modify frozen String>'.
```

Please let me know if this answer satisfies you, or I miss what you were trying to mention.

**Comment by hgani** [comment]
@peterept @yhirose Thanks for the quick response guys. Yes that was my question exactly and I am happy with the answers :)

You can close this issue.

**Comment by yhirose** [comment]
Thanks for the reply!

**Comment by tsauerwein** [comment]
> A MaxMindDB instance doesn't do any write operation after it is created. So we can consider it as an immutable object which is 'thread-safe'.

@yhirose Would it maybe be a good idea to mention this in the readme? Because I had exactly the same question and was about to open a new issue to ask.

**Comment by yhirose** [comment]
@tsauerwein, thanks for the suggestion. I updated the README accordingly.
