### ISSUE TITLE
MaxMind-DB-Writer-perl create mmdb can't read

### ISSUE THREAD

**Issue by zcola** [yhirose/maxminddb#20]
```
cat 1.rb
require 'maxminddb'
db = MaxMindDB.new('/tmp/MaxMind_DB_Writer_perl_create.mmdb')
ret = db.lookup('1.0.16.1')
print ret.found?
[zhangrui@RuiZhangdeMacBook-Air-2 ~ ]$ ruby 1.rb
false%

cat 2.rb
require 'maxminddb'
db = MaxMindDB.new('/tmp/GeoLite2-Country.mmdb')
ret = db.lookup('1.0.16.1')
print ret.found?
[zhangrui@RuiZhangdeMacBook-Air-2 ~ ]$ ruby 1.rb
true%
```
but python maxminxddb two mmdb files can read
```
import maxminddb
import json
reader = maxminddb.open_database('/tmp/MaxMind_DB_Writer_perl_create.mmdb')
result = reader.get('1.0.16.1')
reader.close()
print json.dumps(result, indent=2)
```

**Comment by zcola** [comment]
@yhirose You can `git clone https://github.com/zcola/mmdb-script.git` get it or use `csv_to_mmdb.pl ` to create one. Thanks!

**Comment by zcola** [comment]
Hi
  Any progress?

**Comment by yhirose** [comment]
Sorry for the delay. I confirmed the bug with your test data. I'll take a look at the libmaxminddb source to understand what's missing in the maxmanddb ruby gem.
Thanks for your patience.

**Comment by oschwald** [comment]
Without testing, I'd guess it is the 32 bit record size. Most of the databases released by MaxMind use a 24 bit or 28 bit record size.

**Comment by yhirose** [comment]
@oschwald, thank you for the nice clue.
@zcola, I fixed the problem. Could you get my commit 50ac399, and test it on your machine?
Thanks!

**Comment by zcola** [comment]
Work for me, Thanks a lot.

**Comment by yhirose** [comment]
Thanks for the report!
