### ISSUE TITLE
Finding incorrect geonames

### ISSUE THREAD

**Issue by snapmediateam** [yhirose/maxminddb#22]
Hi,

I am using some test IP addresses with this library and am seeing it return random geonames back.

I am using the MaxMind DB binary, gzipped found here:
http://dev.maxmind.com/geoip/geoip2/geolite2/

Environment:
- Ruby 2.2.4
- Rails 4.2.6

eg.  IP address 199.241.208.206 (which should be a U.S. one)  comes back with 

```
"city" => {
    "geoname_id" => 3173435,
           "names" => {
               "de" => "Mailand",
               "en" => "Milan",
              "es" => "Milán",
             "fr" => "Milan",
             "ja" => "ミラノ",
            "pt-BR" => "Milão",
               "ru" => "Милан"
 }
```

This is my ruby code.

```
    db = MaxMindDB.new('./db/GeoLite2-City.mmdb')
    ret = db.lookup(ip_address)
    ap ret
```

Note: if I use the hive_geoip2 gem, it works fine.

Am I missing something?

**Comment by AlexShmatko** [comment]
Update MaxMind database, I can see US with provided IP address.

**Comment by yhirose** [comment]
@AlexShmatko, thank you very much for the test report.
@snapmediateam, could you try again with the latest database file?
Thank you,
Yuji

**Comment by snapmediateam** [comment]
I am using the latest one from here http://dev.maxmind.com/geoip/geoip2/geolite2/, its not the database as it works with the [hive_geoip2](https://github.com/desuwa/hive_geoip2) gem 

Could it be a Ruby version my Ruby version?

**Comment by yhirose** [comment]
@snapmediateam, I have downloaded the latest GeoLite2-City.mmdb and installed Ruby 2.2.4 through rbenv. It seems it works on my machine. Is your GeoLite2-City.mmdb as same as the following?

    36745923 Mar 24 22:24 GeoLite2-City.mmdb

Here is my result:
```
[master] ~/Dropbox/Projects/maxminddb$ ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin13]

[master] ~/Dropbox/Projects/maxminddb$ cat a.rb
require 'maxminddb'
db = MaxMindDB.new('/Users/yuji/Downloads/GeoLite2-City.mmdb')
ret = db.lookup('199.241.208.206')
p ret

[master] ~/Dropbox/Projects/maxminddb$ ruby a.rb
#<MaxMindDB::Result:0x007fda5380c9a8 @raw={"city"=>{"geoname_id"=>4570284, "names"=>{"en"=>"Beaufort", "zh-CN"=>"博福特"}}, "continent"=>{"code"=>"NA", "geoname_id"=>6255149, "names"=>{"de"=>"Nordamerika", "en"=>"North America", "es"=>"Norteamérica", "fr"=>"Amérique du Nord", "ja"=>"北アメリカ", "pt-BR"=>"América do Norte", "ru"=>"Северная Америка", "zh-CN"=>"北美洲"}}, "country"=>{"geoname_id"=>6252001, "iso_code"=>"US", "names"=>{"de"=>"USA", "en"=>"United States", "es"=>"Estados Unidos", "fr"=>"États-Unis", "ja"=>"アメリカ合衆国", "pt-BR"=>"Estados Unidos", "ru"=>"США", "zh-CN"=>"美国"}}, "location"=>{"latitude"=>32.3289, "longitude"=>-80.6994, "metro_code"=>507, "time_zone"=>"America/New_York"}, "postal"=>{"code"=>"29902"}, "registered_country"=>{"geoname_id"=>6252001, "iso_code"=>"US", "names"=>{"de"=>"USA", "en"=>"United States", "es"=>"Estados Unidos", "fr"=>"États-Unis", "ja"=>"アメリカ合衆国", "pt-BR"=>"Estados Unidos", "ru"=>"США", "zh-CN"=>"美国"}}, "subdivisions"=>[{"geoname_id"=>4597040, "iso_code"=>"SC", "names"=>{"en"=>"South Carolina", "es"=>"Carolina del Sur", "fr"=>"Caroline du Sud", "ja"=>"サウスカロライナ州", "pt-BR"=>"Carolina do Sul", "ru"=>"Южная Каролина", "zh-CN"=>"南卡罗来纳州"}}]}>
```

I really appreciate any extra information that could help me to reproduce the problem.

**Comment by snapmediateam** [comment]
Go figure after hours of figuring out what could be the issue it is actually another gem that is causing the issue.

I have in my gemfile also the "ruby-units" gem, which when I remove returns the result back to normal.

ruby-units must be overriding something and mucking up the parsing of your library.  

Thanks heaps for the debug info :)

**Comment by yhirose** [comment]
No problem. Your report could help other users who may experience the same problem in the future.
Thanks a lot!
