### ISSUE TITLE
Bignum and Fixnum are deprecated in ruby 2.4

### ISSUE THREAD

**Issue by shadowed87** [yhirose/maxminddb#26]
lib/maxminddb.rb:162: warning: constant ::Bignum is deprecated
lib/maxminddb.rb:162: warning: constant ::Fixnum is deprecated

**Comment by yhirose** [comment]
@shadowed87, Thanks for the report. It should be fixed at #23.
Could you make sure that you are using the latest version (0.1.12)?

**Comment by yhirose** [comment]
Please let me know if it's still problem.
