### ISSUE TITLE
time zone info

### ISSUE THREAD

**Issue by morgoth** [yhirose/maxminddb#48]
In first version of geoip there was available time zone information.
Is it provided in geoip2? And if yes, would it be possible to provide it in this gem?

**Comment by yhirose** [comment]
@morgoth, the location result object has the time zone field. Is it what you wanted?
https://github.com/yhirose/maxminddb/blob/master/lib/maxminddb/result/location.rb#L20-L22

**Comment by morgoth** [comment]
Yes, thank you - somehow I missed it.
