### ISSUE TITLE
Does not accept `IPAddr` object as input

### ISSUE THREAD

**Issue by pjg** [yhirose/maxminddb#51]
Devise now defaults to store IP addresses as `inet` columns, which are automatically available as `IPAddr` instances in Rails. It would be very helpful if maxminddb accepted such instance as an input param.

Example:

```ruby
MAXMIND_DB = MaxMindDB.new(GeoLite2City::DB_PATH)
MAXMIND_DB.lookup(IPAddr.new('153.19.48.1'))
=> IPAddr::AddressFamilyError: address family must be specified
```

This method should be updated: 
https://github.com/yhirose/maxminddb/blob/master/lib/maxminddb.rb#L180

I would be able to provide a patch if you agree with the above reasoning.

**Comment by yhirose** [comment]
Please let me know when your PR becomes ready!
