### ISSUE TITLE
Error during lookup with latest GeoLite2-City

### ISSUE THREAD

**Issue by elsurudo** [yhirose/maxminddb#55]
Hello!

Recently I had to upgrade the download path of the DB and re-deploy my app which uses this gem, due to Maxmind licensing changes.

However, I am now getting errors doing lookups (both with regular and low-memory reader):

```
irb(main):016:0> GEOIP = MaxMindDB.new(Rails.root.join(ENV['maxmind2_city_db_path']), MaxMindDB::LOW_MEMORY_FILE_READER)
=> #<MaxMindDB::Client: DBPath:'/app/GeoLite2-City.mmdb'>
irb(main):017:0> GEOIP.metadata
=> {"binary_format_major_version"=>2, "binary_format_minor_version"=>0, "build_epoch"=>1580229618, "database_type"=>"GeoLite2-City", "description"=>{"en"=>"GeoLite2 City database"}, "ip_version"=>6, "languages"=>["de", "en", "es", "fr", "ja", "pt-BR", "ru", "zh-CN"], "node_count"=>3786198, "record_size"=>28}
irb(main):018:0> GEOIP.lookup '89.73.253.152'
Traceback (most recent call last):
        1: from (irb):18
EOFError (end of file reached)
irb(main):019:0> GEOIP = MaxMindDB.new(Rails.root.join(ENV['maxmind2_city_db_path']))
=> #<MaxMindDB::Client: DBPath:'/app/GeoLite2-City.mmdb'>
irb(main):020:0> GEOIP.lookup '89.73.253.152'
Traceback (most recent call last):
        1: from (irb):20
NoMethodError (undefined method `ord' for nil:NilClass)
```

The MMDB file looks fine. Any ideas on what could have gone wrong? Thanks for the help.

Btw, I am using the latest gem version of maxminddb (0.1.22).

**Comment by yhirose** [comment]
@elsurudo, thanks for the feedback. It might be the same issue that I had. It was actually my mistake.
https://github.com/maxmind/MaxMind-DB-Reader-ruby/issues/32

Please let me know if it is caused by a different reason.

**Comment by elsurudo** [comment]
Thanks – indeed the buildpack was un-gzipping, but not untarring...
